apiVersion: v1
kind: Service
metadata:
  name: storefront-api
  namespace: reliability-lab
spec:
  type: LoadBalancer
  selector:
    app: storefront-api
  ports:
    - name: http
      port: 80
      targetPort: 8080