apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-api
  namespace: reliability-lab
  labels:
    app: storefront-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storefront-api
  template:
    metadata:
      labels:
        app: storefront-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      nodeSelector:
        agentpool: app
      containers:
        - name: storefront-api
          image: devacr674.azurecr.io/storefront-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: INVENTORY_URL
              value: http://inventory-api:8080
            - name: OTEL_SERVICE_NAME
              value: storefront-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability:4317
            - name: DEPLOYMENT_ENVIRONMENT
              value: dev
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: storefront-api
  namespace: reliability-lab
spec:
  type: LoadBalancer
  selector:
    app: storefront-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
