name: ci-storefront-api

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - feature/github-actions-ci
        paths:
            - "apps/storefront-api/**"
            - ".github/workflows/storefront-api.yaml"
    
    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: apps/storefront-api

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                

            - name: Smoke Test - Start up app
              run: |
                uvicorn app.main:app --host 127.0.0.1 --port 8081 &
                sleep 5
                curl --fail http://127.0.0.1:8081/healthz
                curl --fail http://127.0.0.1:8081/readyz
            
            - name: Build docker image
              run: |
                docker build -t storefront-api-ci:${{github.sha}} .
                docker image ls