name: terraform-teardown

on:
    push:
        branches: 
          - feature/github-actions-ci

        paths:
          - "environments/dev/**"
          - ".github/workflows/terraform-teardown.yaml"



jobs:
    teardown:
        permissions:
          id-token: write

        runs-on: ubuntu-latest
        
        environment: 
          name: terraform-dev
        
        defaults:
          run:
            working-directory: environments/dev
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Az CLI Login
              uses: azure/login@v2
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform-version: "1.14.6"

            - name: Terraform init
              run: terraform init -reconfigure -no-color -input=false

                # 3. Check for proper code formatting syntax
            - name: Terraform destroy
              run: terraform destroy -auto-approve -no-color -input=false

            

            

            