name: terraform-build

on:
    pull_request:
        branches:
          - main

    push:
        branches: 
          - main

        paths:
          - "environments/dev/**"
          - ".github/workflows/terraform-build.yaml"
          - "modules/**"
    
    workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: environments/dev

concurrency: 
  group: aks-dev
  cancel-in-progress: false
      
jobs:
    terraform-plan:
        name: Terraform Plan
        runs-on: ubuntu-latest
        
        #github repo environment skips the review/approval from github actions workflow
        environment: 
          name: terraform-plan
        
        defaults:
          run:
            working-directory: ${{env.TF_WORKING_DIR}}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Az CLI Login
              uses: azure/login@v3
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.14.6"

            # 3. Check for proper code formatting syntax
            - name: Terraform Format Check
              working-directory: ${{github.workspace}}
              run: terraform fmt -check -recursive
              
            # 4. Initialize the workspace and download provider plugins
            - name: Terraform Init
              run: terraform init -input=false

            # 5. Validate the static syntax of your configuration files
            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan -no-color -input=false -out=tfplan

            - name: Display Terraform Plan
              run: terraform show -no-color tfplan

            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                name: terraform-plan-${{github.run_id}}
                path: ${{env.TF_WORKING_DIR}}/tfplan
                retention-days: 1

    terraform-apply:
      if: github.event_name != 'pull_request'
      name: Terraform Apply
      runs-on: ubuntu-latest
      needs: terraform-plan

      #github repo environment; allow review/approval for tf apply
      environment: 
        name: terraform-dev

      defaults:
        run:
          working-directory: ${{env.TF_WORKING_DIR}}

      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Az CLI Login
          uses: azure/login@v3
          with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: "1.14.6"

        - name: Terraform Init
          run: terraform init -input=false
        
        - name: Download tf plan artifact
          uses: actions/download-artifact@v4
          with:
            name: terraform-plan-${{github.run_id}}
            path: ${{env.TF_WORKING_DIR}}

        - name: Terraform Apply
          run: terraform apply -input=false tfplan
    
    bootstrap-kubernetes:
      needs: terraform-apply
      runs-on: ubuntu-latest
      
      #github environment
      environment:
        name: terraform-dev
      
      defaults:
        run:
          working-directory: k8s/apps

      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Az CLI Login
          uses: azure/login@v3
          with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

        - name: AKS credentials 
          run: az aks get-credentials --name dev-aks --resource-group rg-aks-reliability-dev --overwrite-existing

        - name: Apply K8s resources
          run: |
            kubectl apply -f namespace.yaml
            kubectl apply -f services/inventory-api-service.yaml
            kubectl apply -f services/storefront-api-service.yaml